<?php

/**
 * @file
 * OpenEuropa Time Caching module.
 */

declare(strict_types = 1);

use Drupal\Core\Cache\Cache;

/**
 * Implements hook_cron().
 */
function oe_time_caching_cron() {
  /** @var \Drupal\Component\Datetime\TimeInterface $time */
  $time = \Drupal::service('datetime.time');
  /** @var \Drupal\oe_time_caching\Cache\TimeBasedCacheTagGeneratorInterface $generator */
  $generator = \Drupal::service('oe_time_caching.time_based_cache_tag_generator');

  // Invalidate list of time-dependent tags until the current time.
  $datetime = (new \DateTime())->setTimestamp($time->getCurrentTime());
  $tags = $generator->generateInvalidatingTags($datetime);
  Cache::invalidateTags($tags);
}
